AllCops:
  NewCops: enable
  Exclude:
    - tmp/**/*
    - pkg/**/*
    - test/samples/**/*
    - rien_output/**/*
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
